[package]
name = "hydrus-api-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
http = "1.3.1"
musli = { version = "0.0.145", features = ["json"] }
thiserror = "2.0.16"
ureq = "3.1.0"
urlencoding = "2.1.3"
