[package]
name = "hydrus-api-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_repr = "0.1.20"
thiserror = "2.0.16"
ureq = { version = "3.1.0", features = ["json"] }
urlencoding = "2.1.3"
